// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmuuEOWOvK0tDBWvlMlytkUCKZrSxqeYs',
    appId: '1:373927318970:web:08f4201c9bb5d42ce3f983',
    messagingSenderId: '373927318970',
    projectId: 'chatbot-d3fb6',
    authDomain: 'chatbot-d3fb6.firebaseapp.com',
    storageBucket: 'chatbot-d3fb6.firebasestorage.app',
    measurementId: 'G-GYZX8H36NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO3c7M7WuVeJoi4o-2k0s3HFXGty2v1Vc',
    appId: '1:373927318970:android:52c42e454c2287b8e3f983',
    messagingSenderId: '373927318970',
    projectId: 'chatbot-d3fb6',
    storageBucket: 'chatbot-d3fb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI4pz_Jjm_xEXOAviBdKwgPFwQlwFY7v0',
    appId: '1:373927318970:ios:8df8a3db41e6e9b1e3f983',
    messagingSenderId: '373927318970',
    projectId: 'chatbot-d3fb6',
    storageBucket: 'chatbot-d3fb6.firebasestorage.app',
    iosBundleId: 'com.example.unitAssistantChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI4pz_Jjm_xEXOAviBdKwgPFwQlwFY7v0',
    appId: '1:373927318970:ios:8df8a3db41e6e9b1e3f983',
    messagingSenderId: '373927318970',
    projectId: 'chatbot-d3fb6',
    storageBucket: 'chatbot-d3fb6.firebasestorage.app',
    iosBundleId: 'com.example.unitAssistantChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmuuEOWOvK0tDBWvlMlytkUCKZrSxqeYs',
    appId: '1:373927318970:web:beed43220136284ee3f983',
    messagingSenderId: '373927318970',
    projectId: 'chatbot-d3fb6',
    authDomain: 'chatbot-d3fb6.firebaseapp.com',
    storageBucket: 'chatbot-d3fb6.firebasestorage.app',
    measurementId: 'G-SGE57190L6',
  );
}
